apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Application}}-ingress
  namespace: {{.Namespace}}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    {{if .InternalAccessOnly}}nginx.ingress.kubernetes.io/whitelist-source-range: "{{.IPs}}"{{end}}
spec:
  rules:
  - host: '{{.Environment}}-{{.Application}}.vgs.com'
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{.Application}}-service
            port:
              number: {{.Deployment.Port}}