apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.ProjectName}}-ingress
  namespace: {{.Namespace}}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: '{{.Environment}}-{{.ProjectName}}.vgs.com'
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{.ProjectName}}-service
            port:
              number: {{.Port}}