apiVersion: v1
kind: Service
metadata:
  name: {{.ProjectName}}-service
  namespace: {{.Namespace}}
spec:
  selector:
    app: {{.ProjectName}}
  ports:
    - protocol: TCP
      port: {{.Port}}
      targetPort: 33449